Hardrock EamilOTP Improvements
wso2-extensions/identity-otp-integration-endpoints pull request #9
Opened 2022-11-08 04:44 UTC by Ushani-Athu

Added email otp expiry time in the API call

2022-11-08 13:23 UTC, LahiruLS requested changes
Lets revert the API version as discussed in the review

2022-11-08 18:10 UTC, LahiruLS approved these changes

2022-11-09 03:56 UTC, LahiruLS requested changes

2022-11-09 03:56 UTC, LahiruLS commented on pom.xml
> +        <org.wso2.carbon.extension.identity.emailotp.common.version>4.0.6
Let's change this version to 4.1.1

2022-11-09 04:42 UTC, rksk approved these changes

2022-11-09 04:43 UTC, merged